server:
  port: 8091

spring:
  application:
    name: transaction-service

#Datasource
  datasource:
    url: jdbc:mysql://localhost:3306/transactiondatabase
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:{cipher} df38097b1aec659ee5529fc39aeb448fd360e7702e3a802e33765b25be6413ac

#Jpa
  jpa:
    hibernate:
      ddl-auto: update
  activemq:
    broker-url:

#Kafka
  kafka:
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: "*"

#Jeager
tracing:
  url: http://localhost:4318/v1/traces

#Actuator
management:
  tracing:
    sampling:
      probability: 1.0

#Variable
jwkSetUri: http://localhost:8088/oauth2/jwks
jwtAuthoritiesClaimName: authorities
issuer: http://localhost:8088

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
